export const ProductTypes = {
  FULL_GAME_UPGRADE: 'Full Game Upgrade',
  DEMO: 'Demo',
  SOUNDTRACK: 'Soundtrack',
  APPLICATION: 'Application',
  STOREFRONT_PS2_CLASSIC: 'STOREFRONT_CLASS.PS2_CLASSIC',
  FULL_GAME: 'Full Game',
  BETA: 'Beta',
  AVATAR: 'Avatar',
  BUNDLE: 'Bundle',
  STOREFRONT_PS1_CLASSIC: 'STOREFRONT_CLASS.PS1_CLASSIC',
  SUBSCRIPTION: 'Subscription',
  GAME_PACK: 'Game Pack',
  VIRTUAL_CURRENCY: 'Virtual Currency',
  TRIAL: 'Trial',
  PS2_HD_PLUS: 'PS2 HD+',
  GAME: 'Game',
  THEME: 'Theme',
  FULL_GAME_TRIAL: 'Full Game Trial',
  PLAYABLE: 'Playable',
  ADD_ON: 'Add-On',
};
